[package]
name = "distribution"
version = "0.1.0"
edition = "2021"

# Enable full optimizations in release mode
[profile.release]
opt-level = 3
lto = "fat"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.19"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
uuid = { version = "1.10.0", features = ["v4", "serde"] }
bytes = "1.7.2"
env_logger = "0.11.5"
futures-util = { version = "0.3.31", default-features = false }
sha2 = "0.11.0-pre.4"
regex = "1.11.0"
tokio-util = "0.7.12"
async-trait = "0.1.83"
chrono = "0.4.38"
lazy_static = "1.5.0"
log = "0.4.22"
http-body-util = "0.1.2"
hyper = { version = "1.4.1" , features = ["full"]}
hyper-util = { version = "0.1.9", features = ["tokio"] }
serde_urlencoded = "0.7.1"
hex = "0.4.3"
